### ISSUE TITLE
Support for optional nullchecks in constructors 

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#1]
Although not necessary if you never use null (compiler plugin, anyone?), a mechanism ensuring that null never slip into a data-structure is expected by some user.
Null checks in generated code will be triggered by:
```@Data(arguments = checkedNotNull)```

**Comment by talios** [comment]
I was just toying with some code and noticed this.  The current constructors don't check/enforce `null` checks, but the `getXXX` methods that return `Optional.of()` however do. JDK8's `Optional` class requires that values submitted to `of` be non-null. The `ofNullable()` variant safely handles the null and returns `Absent`.

By not having the null check enforcement at creation time, we would end up with a position where `modXXX` calls could happily work with `null`'s but not `getXXX` - the inconsistency would be annoying.

The JDK8 classes use:

    Objects.requireNonNull(value);

which is a standard method for null checking.

**Comment by jbgi** [comment]
Yes. currently derive4j assumes that ```null``` does not exist, which is the reasonable stance (you cannot reason about you code in the presence of null).
But I know that in large teams some programmers will invariably introduce ```null``` so  you want to have a way to detect them as soon as possible.
Yes, I should use ```Objects.requireNonNull();``` for jdk8 only flavours.
