### ISSUE TITLE
Add support for JavaSlang 2.0 as a Flavour

### ISSUE THREAD

**Issue by talios** [derive4j/derive4j#11]
After playing with Derive4J for even just an evening, I think having support for [JavaSlang](http://javaslang.com) from @danieldietrich would be a great addition once the 2.0 release it made.

This would be a natural fit alongside the other flavours - reusing JavaSlangs `Option` and `Function2`. Adding generators for `tryEmailAddress` along side `getEmailAddress` when using JavaSlang flavour may also be a potentially nice addition.

**Comment by jbgi** [comment]
What should be the signature of ```tryEmailAddress```? (I'm not familiar with javaslang idioms)

**Comment by talios** [comment]
Pretty much the same as `setEmailAddress` but instead of returning `Option<String>` it would return `Try<String>`.

Basically, a `Try` is an encoding around `try/catch/throw` and either returns a `Success` or `Fail` instance. `Fail` containing the exception - essentially it's a more strict variation of an `Either`.

If the current flavour code just describes the types that are used in the common generated code, adding these extra methods may be more than just _adding a flavour_ and may best be skipped initially, and treated as a separate issue.

**Comment by jbgi** [comment]
There is no exception involved so I don't really think returning a Try is a good idea. What I would suggest is that javaslang add something like a ```Try<A> failOnAbsent(Supplier<Exception> ifAbsent)``` on ```Option``` to easily convert from an ```Option``` to a ```Try```.
/cc @danieldietrich

**Comment by danieldietrich** [comment]
`Option`, `Try` and most other Javaslang 2.0.0 types are of type `Value` which has various conversion methods. One of them is `toTry()` (using a `NoSuchElementException` if the value is absent).

Currently we may write

```java
option.toTry().onFailure(ignored -> { throw new AnotherException(); });
```

We may add an additional `Value.toTry(Supplier<Exception>)`.

**Comment by danieldietrich** [comment]
Now Javaslang 2.0.0-RC1 has `Option.toTry(Supplier<? extends Throwable>)`.

_Note: I also don't like the `? extends` and `? super` stuff but there are real world use cases where they are needed. Examples: javaslang/javaslang#352_

**Comment by talios** [comment]
@jbgi Right, no exception so not really needed. Tho I suspect an exception _may_ occur if one has used derive4j's _lazy_ construct. That's an outlier case tho I guess.

**Comment by jbgi** [comment]
@talios values constructed via the lazy constructors (provided the expression does not throw) should behave exactly the same than strictly constructed value.
As an aside, getters/setters/pattern-matching only relies on the abstract 'match' method  so you can totally use other means to construct "```@Data```" instances than the constructors generated by derive4j.

**Comment by talios** [comment]
+2! Look forward to trying this out.
