### ISSUE TITLE
Manage annotated inner classes

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j#14]
Given these classes :

    @Data(flavour = Flavour.FJ)
    public abstract class Product<T> {
      // all the stuff needed...
      
      // ...and then
      @Data(flavour = Flavour.FJ)
      public abstract class Seminar<T> {
         // all the stuff needed...
      } // end of Seminar
          
    } // end of Product

only the `Products` class gets generated. It would be nice if annotated inner classes could be parsed and get their utilities generated just as top level ones.

**Comment by jbgi** [comment]
The problem probably comes from ```Seminar``` missing the ```static``` keyword.
Need to add a nice error message pointing to that.

**Comment by gneuvill** [comment]
Bum. Sorry for the noise, I indeed forgot the static modifier (so much modifiers in java...). Thanks !
