### ISSUE TITLE
Add support for varargs in datatype definitions

### ISSUE THREAD

**Issue by talios** [derive4j/derive4j#19]
Would be it possible to add support for varargs:

    interface Cases<R> {
      R develop(Job job, Job... dependencies);
      R review(Job job, Job... dependencies);
    }

generators constructors like:

    public static JobType develop(Job job, Job[] dependencies) {
    ...

It would be handy if the constructor method matched the vararg definition.

**Comment by jbgi** [comment]
Arrays are painful to work with. I see how varargs can be useful in the constructor signature but I don't think anyone would want to work with them when pattern matching on the datatype. plus that would mean the datatype is mutable... 
In your example I think you would be better of using a datatype like ```NonEmpty<T>``` that may already provide the varargs constructor.

**Comment by talios** [comment]
True - was more just thinking having the consistency would be nice.  Maybe a warning emitted if you happen to use varargs?

The code in question I ended up switching for a javaslang `HashSet` which ended up making the code cleaner in the end as well for other reasons.

**Comment by jbgi** [comment]
I agree that consistency is important, will have a look at it.

**Comment by jbgi** [comment]
I also fixed some non compiling code in generated hashcode/equals/toString in presence of arrays.

**Comment by talios** [comment]
Awesome :)
