### ISSUE TITLE
Add support for a la carte derivation

### ISSUE THREAD

**Issue by talios** [derive4j/derive4j#22]
Last week I was experimenting with reworking some existing $work code ( using jADT ) to use derive4j and whilst it worked well, and the code translated fairly seamlessly, I started noticed weird parse/completion errors in IntelliJ.

It seems IntelliJ by default stops parsing files if there over 2500 lines long, and the derive4j generated source file in question was something like 60,000 lines.

In this particular instance, once an object has been created, we have no desired to have mutations, so don't really need any of the set/mod support functions to get generated ( also saving a lot of lambdas being compiled ).

As a simple solution ( other than increasing the rather hidden setting for IntelliJ completion ) was to have a new Flavour.None for derive4j that prevented the generation of get/set/mod methods, leaving you only with the constructors.

Would something like this be useful to anyone else? Or would a more generic (disable set, disable mod, disable get) generation control across flavours be more useful?

**Comment by jbgi** [comment]
:+1: to
> a more generic (disable set, disable mod, disable get) generation control

**Comment by jbgi** [comment]
I can add an enum
```Derivation = Getters | Setters | FluentPatternMatching```
and a new attribute ```Derivation[] omit() default {}``` to ```@Data```
Also moving all public static methods at the top of the generated file could help get important stuff under the 2500 lines threshold of Idea.
@talios, WDYT?

**Comment by talios** [comment]
`Derivation` sounds good. as does moving the static methods to the top.

Would it be worth considering genererating the setters/mods/matching into separate classes as well? Having the single class is nice, but may not scale?

Ideally one should probably not have this amount of cases in a single set of cases tho, which is one of the reasons I was looking at switching to derive4j in for this piece of code ( aside from jADT being unmaintained ).

Since we're starting to get a lot of commands/cases in this piece of code ( essentially an immutable set of events in a CQRS style system, but much more minimal ) we're wanting to look at breaking them into smaller set's of cases with a common super interface which dervie4j's syntax offers quite nicely.

**Comment by jbgi** [comment]
@talios 
I'm going to add the following annotation property in ```@Derive```:
```java
public @interface Derive {
  // ...
  Make[] make() default { lambdaVisitor, constructors, getters, modifiers,
                          lazyConstructor, patternMatching, catamorphism };
  // ...
}
```
So that one can override the default and make derive4j only generate what is explicitly defined.
Is that ok for you?
(Derive4j will take care of dependencies. ie if you specify only ```modifiers``` then ```constructors``` will be automatically generated as well even if not mentioned explicitly)

**Comment by talios** [comment]
+10 that looks good to me.
