### ISSUE TITLE
[Q] Method must have one, and only one, type variable

### ISSUE THREAD

**Issue by nobeh** [derive4j/derive4j#23]
Consider the following example:

```java
@Data(flavour = Flavour.JDK)
public abstract class MyMap<A, B> {

  public interface MyMapVisitor<A, B> {
    MyMap<A, B> EmptyMap();
    MyMap<A, B> Insert(Pair<A, B> argPair, MyMap<A, B> argMap);
  }

  public abstract MyMap<A, B> match(MyMapVisitor<A, B> visitor);

}
```

and I get the following on `mvn clean compile`:

```
Method must have one, and only one, type variable (without bounds) 
that should also be the method return type.
```

which is from [AdtParser#144][1].

What am I doing wrong?

[1]: https://github.com/derive4j/derive4j/blob/master/processor/src/main/java/org/derive4j/processor/AdtParser.java#L144

**Comment by jbgi** [comment]
The message is about the match method. (that should be of the form ```public abstract <R> R match(Visitor<.., R> visitor);```)

I posted the correct encoding in https://github.com/sviperll/adt4j/issues/39#issuecomment-178467550
(also JDK is the default Flavour)

**Comment by nobeh** [comment]
I have tried two cases and both different issues. 

### Case 1

Having

```java
@Data(flavour = Flavour.JDK)
public abstract class MyMap<A, B> {

  public interface MyMapVisitor<A, B, M> {
    M EmptyMap();
    M Insert(Pair<A, B> argPair, M argMap);
  }

  public abstract <M> M match(MyMapVisitor<A, B, M> visitor);
}
```

The following is generated which has compile error on type `M`:

```java
  private static final class Insert<A, B> extends MyMap<A, B> {
    private final Functional.Pair<A, B> argPair;
    private final M argMap;

    Insert(Functional.Pair<A, B> argPair, M argMap) {
      this.argPair = argPair;
      this.argMap = argMap;
    }

    @Override
    public <M> M match(MyMap.MyMapVisitor<A, B, M> visitor) {
      return visitor.Insert(this.argPair, this.argMap);
    }
  }
```

which complains about type of `M` that cannot be resolved.

### Case 2

The more correct definition is

```java
@Data(flavour = Flavour.JDK)
public abstract class MyMap<A, B> {

  public interface MyMapVisitor<A, B, M extends MyMap<A, B>> {
    M EmptyMap();
    M Insert(Pair<A, B> argPair, M argMap);
  }

  public abstract <M extends MyMap<A, B>> M match(MyMapVisitor<A, B, M> visitor);
}
```
in which `M` is defined as a sub-type of `MyMap`. This actually must be the case always otherwise
the abstraction is correct.

But then I again start to have the compile error as:

```
Method must have one, and only one, type variable (without bounds) 
that should also be the method return type.
```

This is a bit weird to me because I follow the scheme you explained. I also tried removing `<A,B>` from
`M extends MyMap<A,B>` but with the same result.

I am using JDK 1.8.0u76 and Maven Compiler 3.5.

**Comment by jbgi** [comment]
@nobeh Case 1 is almost correct; you need to change the type of ```argM``` to ```MyMap<A, B>``` (from ```M```). See the link in my previous comment.

It does show that I need to add a validation to the ADT parser so that a correct error is displayed instead of the compile error in generated code that you got.

**Comment by nobeh** [comment]
Thanks, indeed, the actual type should be used with derive4j. Let's see if I can make this code-generator friendly for *destructuring pattern matching*.
