### ISSUE TITLE
GADTs : provide an 'Id' functional interface for type association (unification ?)

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j#27]
Jamais deux sans trois,

Re-reading my example : 

``` java
abstract class Seminar<T> {
    Seminar() {}
    interface Cases<R, T> {
        R Init(SData.Core core, F<Init, T> __);
        R Temp(SData.Core core, SData.Add1 add1, F<Temp, T> __);
    }

  public static final class Init { private Init() {} }
  public static final class Temp { private Temp() {} }
}
```

I realize that the free `F` type (any functional interface would do, right ?) used to associate the `T` type parameter with a concrete (`Init` or `Temp`) type could be profitably (for the newcomer) replaced by a fixed `Id` type provided by derive4j.

What do you think ? Wouldn't it make the intent of that mysterious additional parameter clearer to the boeotian (that I once was) ?

**Comment by jbgi** [comment]
Yes! (this was discussed in https://github.com/sviperll/adt4j/issues/15).
I think a ```Leibniz<A,B>``` in functionaljava would be a good fit for this.

**Comment by jbgi** [comment]
PR ongoing in derive/hkt: https://github.com/derive4j/hkt/pull/18
