### ISSUE TITLE
Generation fails for sum type + "lambda visitor" + non default Flavour

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#28]
see report in https://github.com/datatyped/pfds-java/commit/3487a21371e3cc9a31a959357cab1735dff71bf9 by @rdegnan

**Comment by jbgi** [comment]
@redegan: could you try against 0.6.3?

**Comment by rdegnan** [comment]
It’s working now, great! By the way, I was wondering if you intended to provide a mechanism to plug in custom derivators? For instance, for javaslang it would be awesome to be able to derive Functor, Foldable, Traversable, etc. but that wouldn’t apply to other flavors, or the derivator would differ greatly. I’m thinking of something like Data.Derive in Haskell (https://github.com/ndmitchell/derive <https://github.com/ndmitchell/derive>).

**Comment by jbgi** [comment]
@rdegnan it is the plan, yes. Custom derivators should implements https://github.com/derive4j/derive4j/blob/master/processor-api/src/main/java/org/derive4j/processor/api/Derivator.java (and will be retrieve via ServiceLoader).
In the next months or so, I plan to derive Equal/HashShow/Monoid from functional-java through the project https://github.com/derive4j/derive4j-fj

**Comment by jbgi** [comment]
and yes, the name of the project is "derived" from https://github.com/ndmitchell/derive !
