### ISSUE TITLE
Alternative lazy value implementations

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#30]
Additionally from the current synchronized-based implementation, two alternative implementations should be available and configurable via annotation:
* one based on ```AtomicReference<Adt>```
* one based on ```AtomicReference<WeakReference<Adt>>```

which allow better throughput than the synchronized based implementation at the price of possible concurrent evaluation.

**Comment by danieldietrich** [comment]
Hi, do you think that it makes a big difference to have them when using the 'double checked locking' pattern?

```java
transient volatile Supplier<? extends T> supplier; // initialized on construction
volatile T value;

T get() {
    if (supplier != null) {
        synchronized (this) {
            if (supplier != null) {
                value = supplier.get();
                supplier = null; // free mem
            }
        }
    }
    return value;
}
```

**Comment by jbgi** [comment]
https://github.com/scalaz/scalaz/issues/1103 suggests that it is significant, but I'm doing to benchmark.

**Comment by danieldietrich** [comment]
Thx

**Comment by danieldietrich** [comment]
I implemented a similar test you mentioned above (scalaz). Would be interesting to see the difference when you implemented alternative lazy value impls.

```java
public class Bench {

    public static void main(String[] args) {

        // Average time after 100 iterations: 6.560000 ms
        timed(() -> scala.collection.immutable.Stream.range(0, 100000, 1, new scala.math.Numeric.IntIsIntegral$()).length(), 100, 10);

        // Average time after 100 iterations: 7.390000 ms
        timed(() -> javaslang.collection.Stream.range(0, 100000).length(), 100, 10);

        // Average time after 100 iterations: 0.580000 ms
        timed(() -> java.util.stream.IntStream.range(0, 100000).boxed().count(), 100, 10);
    }

    static void timed(Runnable stuff, int iterations, int warmup) {
        long vs = 0;
        for (int i = 0; i < warmup; i++) {
            System.gc(); // try to get rid of potential GC pauses
            stuff.run();
        }
        for (int i = 0; i < iterations; i++) {
            System.gc(); // try to get rid of potential GC pauses
            long t = System.currentTimeMillis();
            stuff.run();
            vs += System.currentTimeMillis() - t;
        }
        System.out.printf("Average time after %d iterations: %f ms\n", iterations, ((double) vs) / iterations);
    }

}
```

**Comment by jbgi** [comment]
@danieldietrich this atomicref implI benchmark at 2x speed:
```java
 private static final class Lazy<A> extends ListA<A> {

    private final AtomicReference<Supplier<ListA<A>>> expression;

    private ListA<A> evaluation;

    Lazy(Supplier<ListA<A>> listA) {
      this.expression = new AtomicReference<>(listA);
    }

    private ListA<A> eval() {
      final Supplier<ListA<A>> _expression = this.expression.get();
      if (_expression == null) {
        return evaluation;
      }
      final ListA<A> _evaluation = _expression.get();
      if (expression.compareAndSet(_expression, null)) {
        return _evaluation;
      }
      return evaluation;
    }

    @Override
    public <X> X list(Supplier<X> nil, BiFunction<A, ListA<A>, X> cons) {
      return this.eval().list(nil, cons);
    }
  }
```

**Comment by jbgi** [comment]
(edit: removed false implementation)

**Comment by jbgi** [comment]
my initial benchmarks do not show any improvement with AtomicRef over synchronized in mono-threaded code. Need to check the scalaz result to understand better.

**Comment by danieldietrich** [comment]
Peter Lawrey suggests to use volatile over AtomicReference (but I think it does not match our use-case regarding synchronized) http://stackoverflow.com/questions/281132/java-volatile-reference-vs-atomicreference/497150#497150.

**Comment by jbgi** [comment]
@danieldietrich I used your Bench with my List implementation and
```java
    static final int COUNT = 500000;
    static final int ITERATIONS = 200;
    static final int WARMUP = 100;
```
results:
* not synchronized:
Average time after 200 iterations: 14.260000 ms

* Lazy synchronized:
Average time after 200 iterations: 18.755000 ms

* Lazy AtomicReference:
Average time after 200 iterations: 25.510000 ms

* Lazy synchronized WeakReference:
Average time after 200 iterations: 19.900000 ms

* Lazy AtomicReference of WeakReference:
Average time after 200 iterations: 18.370000 ms

So it looks like usage of AtomicReference are only slightly useful in conjunction with weak reference (as in the scalaz case).

**Comment by danieldietrich** [comment]
@jbgi great, interesting insights! I will stay with the one impl in my case - simple and safe. If possible I prefer the "give me no configuration hell, just give me one option" API design principle :-)

**Comment by jbgi** [comment]
Closing as there is very few use cases for weak laziness and the current double check locking idiom is fast enough.
