### ISSUE TITLE
Add support for a HighJ flavour

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#32]
https://github.com/DanielGronau/highj

**Comment by jbgi** [comment]
https://github.com/DanielGronau/highj

**Comment by jbgi** [comment]
@DanielGronau, @clinuxrulz: I found that the constructor methods of Either and Maybe are a bit verbose, do you plan to keep them as is or would you rather drop the 'new' prefix to be more in line with other fp libraires?

I ask because the name of the methods will be hard-coded in derive4j (as well as the qualified name of Maybe, Either and F1). So it would be better if they not change just after the derive4j release.

**Comment by DanielGronau** [comment]
The constructor methods started actually as Left, Right, Just, Nothing, I changed them to to follow the Java convention of small method names (and couldn't bring myself to call them left, right etc). 

However, I have no strong opinion about this, and wouldn't mind to switch back to the old uppercase names. Then there is still the question concerning the lazy counterparts. I found out that using the same name for a lazy version passing a Supplier is a bad idea.

**Comment by jbgi** [comment]
yes, using the same name for the lazy constructor can break method reference type inference.

@DanielGronau could you drop me a note in this issue when the HighJ has settled on those points ?

**Comment by DanielGronau** [comment]
@jbgi We moved `Maybe` and `Either` to `org.highj.data`, and `F1` to `org.highj.function`. Further, we changed the constructor methods to upper-case.

**Comment by jbgi** [comment]
@DanielGronau perfect. Need to sort out #34 and #35 and will release 0.9 shortly!

**Comment by jbgi** [comment]
@clinuxrulz @DanielGronau Derive4J 0.8 with the HighJ flavour should now be available on maven central!

**Comment by DanielGronau** [comment]
Thank you, I updated the dependency.
