### ISSUE TITLE
Make the @Data annotation available for package (package-info.java)

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#35]
Components of the annotation would then be overridable:
package and class annotated deeper in the package hierarchy override the configuration found in annotated packages closer to the root.

This will alleviate the need to repeat the same ```@Data``` configuration over and over on each data type in a given project.
Also the name of the generated class will support template, ie something like `@Derive(inClass="{ClassName}Impl")`.

**Comment by gneuvill** [comment]
:+1: 

Might be worth considering the case of 'package like' classes also (i.e final classes with a private constructor that serve only as a namespace and container for static types and functions) ?

**Comment by jbgi** [comment]
another way suggested by @talios:
> Maybe explore the "annotation of annotations" approach, where I could have my own annotation, to which I add preferred styling/setup/config I always use.

**Comment by jbgi** [comment]
Closed in favor of #56.
