### ISSUE TITLE
Auto Type unification might not always be wanted.

### ISSUE THREAD

**Issue by clinuxrulz** [derive4j/derive4j#37]
I've noticed when having something like.

```
 . . .
    interface Cases<R,A> {
        R DoSomething(String x, F<Integer,A> k);
    }
 . . .
```

That it generates a Type constructor ```DoSomething(String x)``` without the ```k```. It uses the Identity function for us.

However this might not always be the only function we would want to use.

For Example. Defining an F-algebra for the use in a free monad. Then defining a Functor instance for the F-algrebra becomes impossible, because we do not have ```DoSomething(String x, F<Integer,A> k)``` type constructor.

Maybe auto-generate both type constructors?

**Comment by clinuxrulz** [comment]
In the above example ```k``` is the continuation for the remainder of the computation. (not a type unification really)

**Comment by jbgi** [comment]
@clinuxrulz thanks for the report. I see, ```->``` is really not an ideal type witness at all. we really need ```Leibniz``` in hkt.
Until then, I'm thinking of automatically generate the unification only if the function argument name start with ```id``` or ```unify```.
Will release a bug fix soon.

**Comment by jbgi** [comment]
@clinuxrulz should be ok with 0.8.1.

**Comment by clinuxrulz** [comment]
@jbgi thank you.
