### ISSUE TITLE
Ability to add annotations to generated classes

### ISSUE THREAD

**Issue by AndreasVoellmy** [derive4j/derive4j#43]
It would often be nice to have sensible ToString implementations on the generated classes. One way of providing toString() is to use lombok's @ToString annotation on the generated class. This could be enabled by being able to specify which annotations should apply to the generated classes.

**Comment by jbgi** [comment]
Hi Andreas,
derive4j can already generate a sensible `toString()`, for that you need to declare the method `abstract` in the base class. ie:
```java
  @Override
  public abstract String toString();
```
same for `equals`/`hashCode`.
See also https://github.com/derive4j/derive4j#equals-hashcode-tostring

**Comment by jbgi** [comment]
@AndreasVoellmy can this issue be closed, or do you have other use cases?
In the long run there will be a "plugin" api to derive4j that should allow to generate custom "type classes".
