### ISSUE TITLE
Support of user defined annotated anotations, overriding and templating

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#56]
- support for user defined annotation alias. Ie, data type could be annotated with a custom annotation `@data` defined as:
```java
@Data(flavour = Flavour.HighJ,
    value = @Derive(inClass = "{ClassName}Impl", withVisibility = Visibility.Package))
public @interface data {
}
```
- config of annotations can be modified/completed through stacking multiple levels of annotated annotations (eg. you can add additional `make` or change just the `visibility`), also `@Derive` can optionally be defined directly on a data type or annotation (without being wrapped in a `@Data`.

(Thanks to @talios for the original feature design idea)

**Comment by talios** [comment]
Nice! `@Data` will still work as existing as well tho right?

**Comment by jbgi** [comment]
@talios, yes.

**Comment by jbgi** [comment]
@talios, @binkley 0.10 has been released with this feature (among other things, see https://github.com/derive4j/derive4j/milestone/15?closed=1). See also [documentation of this feature](https://github.com/derive4j/derive4j#dry-annotation-configuration)
