### ISSUE TITLE
Conflict with other annotation processors

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j#60]
Just tried the new (0.10) version with Lombok on the classpath : my project doesn't compile anymore (Lombok has been kind of muted).

I think it is because `DeriveProcessor` now declares `@SupportedAnnotationTypes("*")` **AND** its `process` method always returns `true` (should be `false`, isn't it ?)

**Comment by jbgi** [comment]
whoops! releasing 0.10.1 tonight
