### ISSUE TITLE
Could not find instance derivator for fj.Equal and InstanceConfig(Optional.empty, Optional.empty)

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j#69]
No idea why, but in `DerivingProcessor.derivedInstance` the `derivators` Map is empty...

**Comment by jbgi** [comment]
Looks like a classpath issue, are you sure the derive4j-fj is in the annotation processing classpath? Or do you have a small project to reproduce the issue?

**Comment by gneuvill** [comment]
Nevermind @jbgi, I fucked up with maven once again... Sorry for the noise !
