### ISSUE TITLE
Add Vavr flavour

### ISSUE THREAD

**Issue by jbgi** [derive4j/derive4j#71]

**Comment by talios** [comment]
+1000 for this :)

**Comment by jbgi** [comment]
@talios would like to implement this?
There is two class to modify:
First add Vavr flavour in https://github.com/derive4j/derive4j/blob/master/annotation/src/main/java/org/derive4j/Flavour.java
Then do a ./gradlew build
Then make the DeriveUtilsImpl class compile, by adding the vavr case in:
https://github.com/derive4j/derive4j/blob/3b6d687d6cd49e445a946f1d1042ea3e274187f6/processor/src/main/java/org/derive4j/processor/DeriveUtilsImpl.java#L167

**Comment by talios** [comment]
Wish I'd seen this on the weekend ( long weekend holiday ) - will take a stab at it tonight!

**Comment by jbgi** [comment]
Fixed via e7c8046a677e947ad27088d4985fb5b8fd3cbe72
