### ISSUE TITLE
Random bug : compilation pb with static imports of constructors

### ISSUE THREAD

**Issue by gneuvill** [derive4j/derive4j#74]
The following

```java
@HktConfig(generateIn = "_Internal")
final class Internal {
  private Internal() {}

  @FjData
  static abstract class Exchange<A, B, S, T> implements __4<Exchange.µ, A, B, S, T> {
    enum µ {}
    Exchange() {}

    interface Cases<R, A, B, S, T> {
      R Exchange(F<S, A> sa, F<B, T> bt);
    }

    abstract <R> R match(Cases<R, A, B, S, T> cases);

    static final class Instances<X, Y, S> implements
      Functor<__<__<__<Exchange.µ, X>, Y>, S>> {

      @Override
      public <A, B> Exchange<X, Y, S, B> map(F<A, B> f, __<__<__<__<Exchange.µ, X>, Y>, S>, A> p) {
        return _Internal
          .asExchange(p)
          .match((a, b) -> _Exchange.Exchange(a, F1W.lift(f).o(b))); // cannot static import 'Exchange'
      }
    }
  }
}
```

compiles fine. But if I static import the `Exchange` factory method, I **sporadically** get a compilation error stating that the `_Exchange` type could not be found.

This happened using gradle.

N.B: the `fjData` annotation is declared as such : 
```java
@Data(
  flavour = Flavour.FJ,
  value = @Derive(
  inClass = "_{ClassName}",
  withVisibility = Visibility.Same
)
)
public @interface FjData {}
```

**Comment by jbgi** [comment]
@gneuvill the culprit could be the hkt processor: it still does quite a lot of multi-threading. We need to fix that.

**Comment by jbgi** [comment]
It could also be due to the new gradle deamon mode that is not yet very good at annotation processor. Maybe try using gradle with ` --no-daemon` and see if it improve the matter.

**Comment by jbgi** [comment]
oh but now I remember facing similar issues when using annotation processor on inner classes: javac was simply ignoring all the imports of the main class when handling the inner class during the processing phases... or something like that.
I first encounter this problem with auto-value, and searching the web I see lombook users also face similar problems with import used by annotated inner classes. See: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7191796 and similar bug in the java bug tracker.

**Comment by gneuvill** [comment]
> the culprit could be the hkt processor: it still does quite a lot of multi-threading. We need to fix that.

That did the trick. Thanks ! (N.B : there is only one call to parallelStream() in hkt)
