### ISSUE TITLE
Any example about Lens support for VAVR?

### ISSUE THREAD

**Issue by jabrena** [derive4j/derive4j#96]
Hi,

I saw the support for VAVR:
https://github.com/derive4j/derive4j/issues/71

But I didn´t see any example or test.
Can you help me with a guidance.

Many thanks in advance

Juan Antonio

**Comment by jbgi** [comment]
So derive4J generate the getters and setters that you need to instanciate "first class" lenses (and prisms). But the Lens class (and friends) is not provided by derive4j it-self.
I don't know if there exist a lens library for vavr. (there is one for functionaljava: https://github.com/functionaljava/functionaljava/tree/series/5.x/core/src/main/java/fj/data/optic - it could probably be easily adapted for vavr if needed).

But in any case the generated setter functions are composable so can still do some lens like operations with a proper lens library, eg.: https://github.com/derive4j/derive4j/blob/master/examples/src/main/java/org/derive4j/example/Person.java#L53 (the mod* methods are generated by derive4j).

**Comment by jabrena** [comment]
Good morning @jbgi, from a Design criteria, `VAVR` doesn't provide support for Optics out of the box, the project is not oriented to pure functional programming. **Is it possible to create a mini library for the VAVR support for Optics?**

- VAVR (876kb) + VAVR-Derive4j-Optics (Few kb) + Derive4j (197kb) ~= 1MB

I could help in the development

Juan Antonio

**Comment by jbgi** [comment]
Hi Juan,

An optics library for vavr should be independent  of derive4j (so just vavr-optics, not vavr-derive4j-optics).
So if you are interested in using optics with vavr, what I would suggest is that you create this vavr-optics project using this repo as blueprint : 
https://bitbucket.org/atlassian/fugue/src/master/fugue-optics/src/main/java/io/atlassian/fugue/optic/
(you "just" have to replace data-types with their vavr equivalent).

Then, as a follow-up task, one could implement generation of optic instances using derive4j extension mechanism (similar to what have been done for FJ type classes).
I could help reviewing your project or if you have any question.

**Comment by jabrena** [comment]
Thanks for the reply,

I will try it :)

Cheers

Juan Antonio
